### ISSUE TITLE
Sentry 24.8.0 > compatibility? Still ImportError: cannot import name 'UserEmail' from 'sentry.users.models' (unknown location) with 24.8.0

### ISSUE THREAD

**Issue by sraisl** [PMExtra/sentry-auth-ldap#22]
Built a new image with sentry 24.8.0 and sentry-auth-ldap version 24.8.0 but I am still getting:

ImportError: cannot import name 'UserEmail' from 'sentry.users.models' (unknown location)

tried to manually install it in the running container to proof the correct version is installed:

Requirement already satisfied: sentry-auth-ldap in /.venv/lib/python3.11/site-packages (24.8.0)
Requirement already satisfied: django-auth-ldap==4.1.0 in /.venv/lib/python3.11/site-packages (from sentry-auth-ldap) (4.1.0)
Requirement already satisfied: sentry>=23.6.0 in ./src (from sentry-auth-ldap) (24.8.0)
Requirement already satisfied: Django>=2.2 in /.venv/lib/python3.11/site-packages (from django-auth-ldap==4.1.0->sentry-auth-ldap) (5.0.8)
Requirement already satisfied: python-ldap>=3.1 in /.venv/lib/python3.11/site-packages (from django-auth-ldap==4.1.0->sentry-auth-ldap) (3.4.4)
Requirement already satisfied: asgiref<4,>=3.7.0 in /.venv/lib/python3.11/site-packages (from Django>=2.2->django-auth-ldap==4.1.0->sentry-auth-ldap) (3.7.2)
Requirement already satisfied: sqlparse>=0.3.1 in /.venv/lib/python3.11/site-packages (from Django>=2.2->django-auth-ldap==4.1.0->sentry-auth-ldap) (0.5.0)
Requirement already satisfied: pyasn1>=0.3.7 in /.venv/lib/python3.11/site-packages (from python-ldap>=3.1->django-auth-ldap==4.1.0->sentry-auth-ldap) (0.4.5)
Requirement already satisfied: pyasn1_modules>=0.1.5 in /.venv/lib/python3.11/site-packages (from python-ldap>=3.1->django-auth-ldap==4.1.0->sentry-auth-ldap) (0.2.4)

am I doing something wrong? I thought plugin version 24.8.0 should work with sentry >= 23.8.0 ?

**Comment by PMExtra** [comment]
https://github.com/getsentry/sentry/blob/24.8.0/src/sentry/users/models/useremail.py
https://github.com/getsentry/sentry/pull/76134

It should be work. Can you share your image?

**Comment by sraisl** [comment]
not happy with sharing my image (LDAP cert inside), I can share my Dockerfile, but this is quite straight-forward:

```
ARG SENTRY_VERSION=${SENTRY_VERSION:24.8.0}
FROM getsentry/sentry:${SENTRY_VERSION}

RUN apt update && apt upgrade -y
RUN apt install build-essential libsasl2-dev python-dev-is-python3 libldap2-dev libssl-dev -y --no-install-recommends
COPY docker/sentry/. /usr/src/sentry

COPY docker/sentry/cert/xxxyyy.pem /usr/share/ca-certificates/cert/
RUN echo cert/xxxyyy.pem >> /etc/ca-certificates.conf
RUN update-ca-certificates

RUN if [ -s /usr/src/sentry/requirements.txt ]; then pip install -r /usr/src/sentry/requirements.txt; fi

RUN apt-get purge -y --auto-remove build-essential
RUN rm -rf /var/lib/apt/lists/*
```

the contents of requirements.txt: 
```sentry-auth-ldap==24.8.0```

running 'sentry --version' gives: 'sentry, version 24.8.0+1d52e8e0ad95615ba5d7e8c020ad6f65dd03763d'

would be glad for any hint in this...

**Comment by sergey-gr** [comment]
Are you running sentry from [self-hosted repo](https://github.com/getsentry/self-hosted) or something built by yourself?

**Comment by sraisl** [comment]
> Are you running sentry from [self-hosted repo](https://github.com/getsentry/self-hosted) or something built by yourself?

self-built Helm Deployment. But this doesn't have any effect to the image itself, doesn't it? Image is built with the Dockerfile posted above, I compared the files/changes in the image from https://github.com/getsentry/sentry/blob/24.8.0/src/sentry/users/models/useremail.py
https://github.com/getsentry/sentry/pull/76134 and there are no differences

**Comment by sergey-gr** [comment]
I think your problem is related to incorrect paths.

Could you run the following command from your container:

```shell
python -c "from sentry.users.models import UserEmail"
```

**Comment by sergey-gr** [comment]
@sraisl @PMExtra 
In Sentry version [24.8.0](https://github.com/getsentry/sentry/tree/24.8.0/src/sentry/users/models), the `.src/sentry/users/models` folder is missing an `__init__.py` file, causing the models folder to not be treated as a package by Python.

File was added in version [24.9.0](https://github.com/getsentry/sentry/tree/24.9.0/src/sentry/users/models), but fully resolved in Sentry version [24.10.0](https://github.com/getsentry/sentry/tree/24.10.0/src/sentry/users/models).
Iv recommend to upgrade to version 24.10.0 to resolve the issue.

If upgrading is not feasible, you can manually fix the issue by adding the following command to Dockerfile:

```shell
sed -i 's/from sentry.users.models import UserEmail/from sentry.users.models.useremail import UserEmail/g' $(python -c "import site; print(site.getsitepackages()[0])")/sentry_auth_ldap/backend.py
```

This command updates the `backend.py` file in the `sentry-auth-ldap` package to use the correct import path.

Hope this helps!

**Comment by PMExtra** [comment]
I've fixed it in https://github.com/PMExtra/sentry-auth-ldap/commit/d3ea595eb80b17a83e17977a3b80fb7ab1e19659 and released 24.8.1
